name: GitHub Demo
on: [push]
jobs:
  Actions_Demo: 
    runs-on: ubuntu-latest
    steps:
    - run: echo 'Job triggered by ${{github.event_name}}'
    - run: echo 'Running on ${{runner.os}}'
    - name: Check out repo
      uses: actions/checkout@v3
    - run: ls 
    - run: echo 'Job status is ${{job.status}}'
  second-job: 
    runs-on: ubuntu-latest
    steps:
    - run: echo '2nd job'
    - run: pwd
